In [1]:
# 匯入 numpy
import numpy as np

In [2]:
# 顯示 numpy 版本
print(np.__version__)

1.15.4


In [3]:
# 使用 numpy array 函式建立一個 numpy nd-array
a = np.array([2,3,4])
print(a)
print(type(a))      ## numpy.ndarray
print(a.shape)      ## 顯示 array 的 dimension，是一個 tuple，分別表示各個維度的 size
print(len(a.shape)) ## shape 的 size，就是代表 array 的 axes
print(a.dtype)      ## array 的型別
print(a.size)       ## array 總共有多少元素，等同於 shape 所有 item 的乘積

[2 3 4]
<class 'numpy.ndarray'>
(3,)
1
int64
3


In [4]:
# 建立 1d-zero numpy array
a1 = np.zeros((5,))
print('1d array:', a1)

# 建立 2d-zero numpy array
a2 = np.zeros((5,2))
print('2d array:', a2)

# 建立 2d-array
a3 = np.array([(1,2,3), (4,5,6)])
print('2d array:', a3)

# 建立 3d-array
a4 = np.zeros((2,3,4))


1d array: [0. 0. 0. 0. 0.]
2d array: [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
2d array: [[1 2 3]
 [4 5 6]]


In [5]:
# 建立一個 2x3 的矩陣 (透過 zeros 指定)
a = np.zeros((2, 3))
print(a)

# 使用 reshape
b = np.zeros((6,)).reshape(2, 3)
print(b)

# 建立一個對角矩陣
Z = np.eye(3)
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# Numpy indexing
arr = np.array([
    [1, 2, 3, 4],
    [2, 4, 6, 8],
    [3, 6, 9, 12]
])

print(arr.shape)

# 取出某個元素
print(arr[1, 3])

# 取出多個元素 (第一個維度取出 0, 2，第二個維度取出 3, 0)
print(arr[[0, 2], [3, 0]])

# boolean indexing
mask = arr > 5
print(mask)
print(arr[mask])

(3, 4)
8
[4 3]
[[False False False False]
 [False False  True  True]
 [False  True  True  True]]
[ 6  8  6  9 12]


In [7]:
# Numpy Slicing
arr = np.array([0,1,2,3,4,5,6])

# Slicing，用 obj[start:end:step] 表示。start <= elements < end，step =/= 0
print(arr[0:7:2])

# 負的 start 和 end 代表 n - start 和 n - end (n 為 element 數量)
print(arr[-5:-3:1]) # 取 (7-5) ~ (7-3) 兩個元素

# 負的 step 代表反序
print(arr[5:0:-1])

# 取 index=2 之後的元素
print(arr[2:])

[0 2 4 6]
[2 3]
[5 4 3 2 1]
[2 3 4 5 6]
